// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: bridger/bridger.proto

package bridgerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadEmitter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Domain   string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Multiple bool   `protobuf:"varint,3,opt,name=multiple,proto3" json:"multiple,omitempty"`
}

func (x *PayloadEmitter) Reset() {
	*x = PayloadEmitter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridger_bridger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadEmitter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadEmitter) ProtoMessage() {}

func (x *PayloadEmitter) ProtoReflect() protoreflect.Message {
	mi := &file_bridger_bridger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadEmitter.ProtoReflect.Descriptor instead.
func (*PayloadEmitter) Descriptor() ([]byte, []int) {
	return file_bridger_bridger_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadEmitter) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PayloadEmitter) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PayloadEmitter) GetMultiple() bool {
	if x != nil {
		return x.Multiple
	}
	return false
}

type PayloadReceiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  []byte     `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Multiple bool       `protobuf:"varint,2,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Info     *ErrorInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *PayloadReceiver) Reset() {
	*x = PayloadReceiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridger_bridger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadReceiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadReceiver) ProtoMessage() {}

func (x *PayloadReceiver) ProtoReflect() protoreflect.Message {
	mi := &file_bridger_bridger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadReceiver.ProtoReflect.Descriptor instead.
func (*PayloadReceiver) Descriptor() ([]byte, []int) {
	return file_bridger_bridger_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadReceiver) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PayloadReceiver) GetMultiple() bool {
	if x != nil {
		return x.Multiple
	}
	return false
}

func (x *PayloadReceiver) GetInfo() *ErrorInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bridger_bridger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridger_bridger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_bridger_bridger_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_bridger_bridger_proto protoreflect.FileDescriptor

var file_bridger_bridger_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x72,
	0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5e, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x22,
	0x71, 0x0a, 0x0f, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x72,
	0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x3b, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x32,
	0x88, 0x01, 0x0a, 0x07, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x04, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x19, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bridger_bridger_proto_rawDescOnce sync.Once
	file_bridger_bridger_proto_rawDescData = file_bridger_bridger_proto_rawDesc
)

func file_bridger_bridger_proto_rawDescGZIP() []byte {
	file_bridger_bridger_proto_rawDescOnce.Do(func() {
		file_bridger_bridger_proto_rawDescData = protoimpl.X.CompressGZIP(file_bridger_bridger_proto_rawDescData)
	})
	return file_bridger_bridger_proto_rawDescData
}

var file_bridger_bridger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bridger_bridger_proto_goTypes = []interface{}{
	(*PayloadEmitter)(nil),  // 0: bridgerpb.PayloadEmitter
	(*PayloadReceiver)(nil), // 1: bridgerpb.PayloadReceiver
	(*ErrorInfo)(nil),       // 2: bridgerpb.ErrorInfo
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_bridger_bridger_proto_depIdxs = []int32{
	2, // 0: bridgerpb.PayloadReceiver.info:type_name -> bridgerpb.ErrorInfo
	3, // 1: bridgerpb.Bridger.Ping:input_type -> google.protobuf.Empty
	0, // 2: bridgerpb.Bridger.Dispatch:input_type -> bridgerpb.PayloadEmitter
	3, // 3: bridgerpb.Bridger.Ping:output_type -> google.protobuf.Empty
	1, // 4: bridgerpb.Bridger.Dispatch:output_type -> bridgerpb.PayloadReceiver
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bridger_bridger_proto_init() }
func file_bridger_bridger_proto_init() {
	if File_bridger_bridger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bridger_bridger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadEmitter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridger_bridger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadReceiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bridger_bridger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bridger_bridger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridger_bridger_proto_goTypes,
		DependencyIndexes: file_bridger_bridger_proto_depIdxs,
		MessageInfos:      file_bridger_bridger_proto_msgTypes,
	}.Build()
	File_bridger_bridger_proto = out.File
	file_bridger_bridger_proto_rawDesc = nil
	file_bridger_bridger_proto_goTypes = nil
	file_bridger_bridger_proto_depIdxs = nil
}
